apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        # zéro downtime
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: busybox:latest
          command: ["sh", "-c", "echo '<h1>Demo App</h1><p>ENV_NAME: '$ENV_NAME'</p><p>LOG_LEVEL: '$LOG_LEVEL'</p><p>POD_NAME: '$POD_NAME'</p>' > /tmp/index.html && httpd -f -p 80 -h /tmp"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: demo-app-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3