apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev

resources:
  - ../../base
  - resourcequota.yaml
  - limitrange.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml

commonLabels:
  environment: dev