apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  labels:
    app.kubernetes.io/part-of: demo-app
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      - pods
      - services
      - configmaps
      - endpoints
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  # Debug : logs et exec
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources:
      - pods/exec
    verbs: ["create"]

  # Écriture : déploiements et exposition
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources:
      - services
    verbs: ["create", "update", "patch", "delete"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get"]