apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../base
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
  - networkpolicy-ingress.yaml
  - networkpolicy-egress-dns.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: deployment-security-patch.yaml

commonLabels:
  environment: prod